# Generated by Django 3.1.7 on 2021-03-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=100)),
                ('staffemail', models.EmailField(max_length=254)),
                ('staffpassword', models.CharField(max_length=8)),
                ('staffuserrole', models.CharField(max_length=50)),
                ('custumefield', models.CharField(max_length=50)),
            ],
        ),
    ]
