# Generated by Django 3.1.7 on 2021-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managecustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusname', models.CharField(max_length=100)),
                ('cusnumber', models.CharField(max_length=10)),
                ('cusemail', models.EmailField(max_length=254)),
                ('cuspassword', models.CharField(max_length=8)),
                ('cusfield1', models.CharField(max_length=50)),
                ('cusbillname', models.CharField(max_length=50)),
                ('cusbillcountry', models.CharField(max_length=50)),
                ('cusbillstate', models.CharField(max_length=50)),
                ('cusbillcity', models.CharField(max_length=50)),
                ('cusbillphone', models.CharField(max_length=10)),
                ('cusbilzipcode', models.CharField(max_length=10)),
                ('cusbilladdress', models.CharField(max_length=100)),
                ('shipadrsname', models.CharField(max_length=100)),
                ('shipadrscountry', models.CharField(max_length=50)),
                ('shipadrsstate', models.CharField(max_length=50)),
                ('shipadrscity', models.CharField(max_length=50)),
                ('shipadrsphone', models.CharField(max_length=10)),
                ('shipadrszipcode', models.CharField(max_length=10)),
                ('shipadrsaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
