# Generated by Django 3.1.7 on 2021-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_managecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managevendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=100)),
                ('vendornumber', models.CharField(max_length=10)),
                ('vendoremail', models.EmailField(max_length=254)),
                ('vendorpassword', models.CharField(max_length=8)),
                ('vendorfield1', models.CharField(max_length=50)),
                ('vendorbillname', models.CharField(max_length=50)),
                ('vendorbillcountry', models.CharField(max_length=50)),
                ('vendorbillstate', models.CharField(max_length=50)),
                ('vendorbillcity', models.CharField(max_length=50)),
                ('vendorbillphone', models.CharField(max_length=10)),
                ('vendorbillzipcode', models.CharField(max_length=10)),
                ('vendorbilladdress', models.CharField(max_length=100)),
                ('vendorshipadrsname', models.CharField(max_length=100)),
                ('vendorshipadrscountry', models.CharField(max_length=50)),
                ('vendorshipadrsstate', models.CharField(max_length=50)),
                ('vendorshipadrscity', models.CharField(max_length=50)),
                ('vendorshipadrsphone', models.CharField(max_length=10)),
                ('vendorshipadrszipcode', models.CharField(max_length=10)),
                ('vendorshipadrsaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
