# Generated by Django 3.1.7 on 2021-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_managevendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managebankaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankusername', models.CharField(max_length=100)),
                ('bankname', models.CharField(max_length=100)),
                ('accountnumber', models.CharField(max_length=20)),
                ('openingbalance', models.CharField(max_length=10000)),
                ('bankcontact', models.CharField(max_length=10)),
                ('bankaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
