# Generated by Django 3.1.7 on 2021-03-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_managebankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managebanktransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromaccount', models.CharField(max_length=100)),
                ('toaccount', models.CharField(max_length=100)),
                ('transferamount', models.CharField(max_length=20)),
                ('transferdate', models.CharField(max_length=100)),
                ('transferrefrence', models.CharField(max_length=10)),
            ],
        ),
    ]
