# Generated by Django 3.1.7 on 2021-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_managebanktransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managerevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenuedate', models.CharField(max_length=100)),
                ('revenueamount', models.CharField(max_length=100)),
                ('revenueaccount', models.CharField(max_length=100)),
                ('revenuecustomer', models.CharField(max_length=100)),
                ('revenuebankaddress', models.CharField(max_length=100)),
                ('revenuecatagory', models.CharField(max_length=100)),
                ('revenuerefrence', models.CharField(max_length=100)),
            ],
        ),
    ]
