# Generated by Django 3.1.7 on 2021-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_managerevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdate', models.CharField(max_length=100)),
                ('paymentamount', models.CharField(max_length=100)),
                ('paymentaccount', models.CharField(max_length=100)),
                ('paymentvendor', models.CharField(max_length=100)),
                ('paymentbankaddress', models.CharField(max_length=100)),
                ('paymentcatagory', models.CharField(max_length=100)),
                ('paymentref', models.CharField(max_length=100)),
            ],
        ),
    ]
