# Generated by Django 3.1.7 on 2021-03-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managesuperuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superusername', models.CharField(max_length=100)),
                ('superuseremail', models.EmailField(max_length=254)),
                ('superuserpassword', models.CharField(max_length=8)),
                ('superuserrole', models.CharField(max_length=50)),
                ('supercustumefield', models.CharField(max_length=50)),
            ],
        ),
    ]
