# Generated by Django 3.1.7 on 2021-03-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_managesuperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=100)),
                ('planprice', models.CharField(max_length=1000)),
                ('planduration', models.CharField(max_length=500)),
                ('maxiuser', models.CharField(max_length=1000)),
                ('maxicustomer', models.CharField(max_length=1000)),
                ('maxivendor', models.CharField(max_length=1000)),
                ('plandescription', models.CharField(max_length=100)),
            ],
        ),
    ]
