# Generated by Django 3.1.7 on 2021-03-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productservicename', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('productservicedescription', models.CharField(max_length=100)),
                ('saleprice', models.CharField(max_length=50)),
                ('purchaseprice', models.CharField(max_length=50)),
                ('producttax', models.CharField(max_length=50)),
                ('productcatagories', models.CharField(max_length=100)),
                ('productunit', models.CharField(max_length=50)),
                ('producttype', models.CharField(max_length=50)),
                ('productcustomefield3', models.CharField(max_length=100)),
            ],
        ),
    ]
