# Generated by Django 3.1.7 on 2021-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_productservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicecust', models.CharField(max_length=100)),
                ('invoiceissudate', models.CharField(max_length=100)),
                ('invoiceduedate', models.CharField(max_length=100)),
                ('invoicenum', models.CharField(max_length=100)),
                ('catagory', models.CharField(max_length=100)),
                ('invoicerefnum', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=50)),
                ('psitem', models.CharField(max_length=100)),
                ('psquantity', models.CharField(max_length=100)),
                ('psprice', models.CharField(max_length=100)),
                ('pstax', models.CharField(max_length=100)),
                ('psdis', models.CharField(max_length=100)),
                ('psdescription', models.CharField(max_length=50)),
            ],
        ),
    ]
