# Generated by Django 3.1.7 on 2021-03-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_managecreditnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billvendor', models.CharField(max_length=100)),
                ('billdate', models.CharField(max_length=100)),
                ('billduedate', models.CharField(max_length=100)),
                ('billnum', models.CharField(max_length=100)),
                ('billcatagory', models.CharField(max_length=100)),
                ('billordernum', models.CharField(max_length=100)),
                ('billdiscount', models.CharField(max_length=50)),
                ('billitem', models.CharField(max_length=100)),
                ('billquantity', models.CharField(max_length=100)),
                ('billprice', models.CharField(max_length=100)),
                ('billtax', models.CharField(max_length=100)),
                ('billdis', models.CharField(max_length=100)),
                ('billdescription', models.CharField(max_length=50)),
            ],
        ),
    ]
