# Generated by Django 3.1.7 on 2021-03-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_managedebitnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=100)),
                ('contactemail', models.EmailField(max_length=254)),
                ('contactsubject', models.CharField(max_length=100)),
                ('contactmessage', models.CharField(max_length=100)),
            ],
        ),
    ]
