# Generated by Django 3.1.7 on 2021-04-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminregistername', models.CharField(max_length=100)),
                ('adminregisteremail', models.EmailField(max_length=254)),
                ('adminregisterpass', models.CharField(max_length=8)),
            ],
        ),
    ]
